#!/bin/bash

#/
#--------------------------------------------------------------------------
# Mago deploy
#--------------------------------------------------------------------------
#
# This command will create a new nginx host file for a specific domain
# pass the website domain and the folder location, here's an example:
#
# $ mago host mywebsite.com /var/www/mywebsite
#
# The above command will create a new nginx host that will listen
# for a connection coming from mywebsite.com and map it to the
# /var/www/mywebsite/public folder
#    RouterRepo Domain
#/
serverRoot='/var/www/'

DOMAIN_NAME=$1
ROUTE_URL=$2
hostdeploy=$3

# read -p "Nombre de github: " github_name
# git config --global user.name "$github_name"
# read -p "Correo de github: " github_email
# git config --global user.email "$github_email"

# read -p "Nombre de la key ssh private: " keyprivate
eval "$(ssh-agent -s)"
sudo chown mago .ssh
ssh-add /home/mago/.ssh/id_rsa
ssh -T git@github.com


if [ "$ROUTE_URL" = "" ]; then
echo "Url del repositorio a clonar de laravel?"
read ROUTE_URL
fi

if [ "$DOMAIN_NAME" = "" ]; then
echo "Nombre del dominio a usar?"
read DOMAIN_NAME
fi


echo "Ruta a instalar $serverRoot"

cd $serverRoot

git clone $ROUTE_URL "$DOMAIN_NAME"

cd $DOMAIN_NAME

cp .env.example .env

# sh /etc/.mago/mago database init

composer install --optimize-autoloader --no-dev

php artisan key:generate

npm i
npm run prod
# php artisan migrate

php artisan config:cache
php artisan route:cache
php artisan view:cache
# sudo chown -R mago:mago /var/www/$DOMAIN_NAME/.git*
git config --global --add safe.directory /var/www/$DOMAIN_NAME

hostdeploy=$3

read -p "Desea instalar host yes/no: " hostdeploy
if [ "$hostdeploy" = "yes" ]
then
    sudo bash /etc/.mago/host "$DOMAIN_NAME" "$serverRoot$DOMAIN_NAME"
else
   exit
fi
