#!/bin/bash

#/
#--------------------------------------------------------------------------
# Mago deploy
#--------------------------------------------------------------------------
#
# This command will create a new nginx host file for a specific domain
# pass the website domain and the folder location, here's an example:
#
# $ mago host mywebsite.com /var/www/mywebsite
#
# The above command will create a new nginx host that will listen
# for a connection coming from mywebsite.com and map it to the
# /var/www/mywebsite/public folder
#   mago deploy_init
#/
serverRoot='/var/www/'

eval "$(ssh-agent -s)"
ssh-add /home/mago/key/fyndecol
ssh -T git@github.com


echo "Url del repositorio a clonar de laravel?"
read ROUTE_URL

echo "Nombre de la carpeta a nombrar el repo?"
read NAME_FILE

echo "Ruta a instalar $serverRoot"
# mkdir $rootPath
cd $serverRoot

git clone $ROUTE_URL "$NAME_FILE"
cd $NAME_FILE
git config --global --add safe.directory /var/www/fyndecol.com


cp .env.example .env

# sh /etc/.mago/mago database init

composer install

php artisan key:generate

# php artisan migrate

# php artisan db:seed

