#!/bin/bash

#/
#--------------------------------------------------------------------------
# Mago deploy
#--------------------------------------------------------------------------
#
# This command will create a new nginx host file for a specific domain
# pass the website domain and the folder location, here's an example:
#
# $ mago host mywebsite.com /var/www/mywebsite
#
# The above command will create a new nginx host that will listen
# for a connection coming from mywebsite.com and map it to the
# /var/www/mywebsite/public folder
#   mago deploy_init RouterRepo Domain
#/
serverRoot='/var/www/'

eval "$(ssh-agent -s)"
read -p "Nombre de la key privada: " keyprivate
ssh-add /home/mago/key/$keyprivate
read -p "Nombre de la key publica.pub: " keypublic
cat /home/mago/key/$keypublic >> ~/.ssh/authorized_keys
ssh -T git@github.com

DOMAIN_NAME=$1
ROUTE_URL=$2
hostdeploy=$3


if [ "$ROUTE_URL" = "" ]; then
echo "Url del repositorio a clonar de laravel?"
read ROUTE_URL
fi

if [ "$DOMAIN_NAME" = "" ]; then
echo "Nombre de la carpeta a nombrar el repo?"
read DOMAIN_NAME
fi


echo "Ruta a instalar $serverRoot"

cd $serverRoot

git clone $ROUTE_URL "$DOMAIN_NAME"

git config --global --add safe.directory /var/www/$DOMAIN_NAME

cd $DOMAIN_NAME

cp .env.example .env

sh /etc/.mago/mago database init

composer install

php artisan key:generate

npm i

php artisan migrate


hostdeploy=$3

read -p "Desea instalar host yes/no: " hostdeploy
if [ "$hostdeploy" = "yes" ]
then
    sudo bash /etc/.mago/host "$DOMAIN_NAME" "$serverRoot$DOMAIN_NAME"
else
   exit
fi
