#!/bin/bash

#/
#--------------------------------------------------------------------------
# Mago deploy
#--------------------------------------------------------------------------
#
# This command will create a new nginx host file for a specific domain
# pass the website domain and the folder location, here's an example:
#
# $ mago host mywebsite.com /var/www/mywebsite
#
# The above command will create a new nginx host that will listen
# for a connection coming from mywebsite.com and map it to the
# /var/www/mywebsite/public folder
#   mago deploy_init
#  mago deploy fyndecol.com git@github.com:MAGODMA96/Mago_script.git
#/
serverRoot='/var/www/'
echo "porfavor "
read -p "Domain a update: " domain
cd $serverRoot
if ! [ -d $domain ]; then
    redbg "The domain $domain not exists. \n Please Try another one"
    exit
fi

cd $domain
php artisan down --render="errors::503"

git pull origin

composer install --optimize-autoloader --no-dev

php artisan key:generate

npm i

php artisan migrate

php artisan config:cache
php artisan route:cache
php artisan view:cache

php artisan up
