#!/bin/bash

#/
#--------------------------------------------------------------------------
# Mago Environment Launcher
#--------------------------------------------------------------------------
#
# Enter shell as mago user
#
#/

if [ "$(whoami)" != "mago" ]; then
    sudo su - mago
else
    echo "Already logged in as mago"
fi
