#!/bin/bash

bar(){
    cyan "--------------------------------------------------"
}

barNoColor(){
    echo "--------------------------------------------------"
}

setsail(){
	cyan   "                                                  "
	cyan   "                     Mago_script                     "
	purple "                         _                        "
	purple "                     __ )_)__                     "
	purple "                     )_))_))_)                    "
	purple "                     _!__!__!_                    "
	purple "                     \_______/                    "
	blue   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
}

setsailNoColor(){
	echo   "                                                  "
	echo   "                     Mago_script                     "
	echo   "                         _                        "
	echo   "                     __ )_)__                     "
	echo   "                     )_))_))_)                    "
	echo   "                     _!__!__!_                    "
	echo   "                     \_______/                    "
	echo   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
}
